name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version-file: 'go.mod'
    # Install gotestfmt on the VM running the action.
    - name: Set up gotestfmt
      uses: GoTestTools/gotestfmt-action@02b936e80bd5b0e515b98eb8f7d998a60ccca462 # v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      run: make test

